# Generated by Django 6.1.1 on 2026-09-04 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Our Household', max_length=100)),
                ('current_season', models.CharField(choices=[('ALL', 'All / Any Season'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall'), ('WINTER', 'Winter')], default='ALL', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Household Settings',
            },
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('UNCLAIMED', 'Unclaimed Pool'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='UNCLAIMED', max_length=20)),
                ('due_date', models.DateField()),
                ('frequency', models.CharField(choices=[('ONE_OFF', 'One-off'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly'), ('SEASONAL', 'Seasonal')], default='ONE_OFF', max_length=20)),
                ('season', models.CharField(choices=[('ALL', 'All / Any Season'), ('YEAR_ROUND', 'Year-Round'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall'), ('WINTER', 'Winter')], default='YEAR_ROUND', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_chores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
